title: My Personal Blog Website
description: >
  This is my simple blog website where I can host my stuff for the time being

theme: minima
#remote_theme: jekyll/minima

header_pages:
  - about.md

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Marshfellow42" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag